// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.DTO;

namespace SchoolManagement.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20200908010754_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolManagement.DTO.DangKiMonHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt");

                    b.Property<int>("MonHocID");

                    b.Property<int>("SinhVienID");

                    b.Property<DateTime>("UpdateAt");

                    b.HasKey("ID");

                    b.HasIndex("MonHocID");

                    b.HasIndex("SinhVienID");

                    b.ToTable("DangKiMonHoc");
                });

            modelBuilder.Entity("SchoolManagement.DTO.MonHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt");

                    b.Property<int>("Credits");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("UpdateAt");

                    b.HasKey("ID");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("SchoolManagement.DTO.SinhVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt");

                    b.Property<string>("FullName");

                    b.Property<DateTime>("UpdateAt");

                    b.HasKey("ID");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("SchoolManagement.DTO.DangKiMonHoc", b =>
                {
                    b.HasOne("SchoolManagement.DTO.MonHoc", "MonHoc")
                        .WithMany("DangKiMonHocs")
                        .HasForeignKey("MonHocID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SchoolManagement.DTO.SinhVien", "SinhVien")
                        .WithMany("DangKiMonHocs")
                        .HasForeignKey("SinhVienID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
